### ISSUE TITLE
jaccard_similarity() warning messages

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#109]
```
> terms <- readLines("catfish_anat.txt") 
> terms_trim <- trimws(terms) 
> sm <- jaccard_similarity(terms = terms_trim, .colnames = "label")
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
2: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
3: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
4: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
5: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
6: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
```

[catfish_anat.txt](https://github.com/phenoscape/rphenoscape/files/3687298/catfish_anat.txt)

**Comment by hlapp** [comment]
I can't reproduce this @wdahdul, it works perfectly fine for me. The `jaccard_similarity()` function and those that it calls don't do any graphics processing of any kind, so the warning messages don't come from anything rphenoscape does.

**Comment by hlapp** [comment]
And just to note, these are warning messages. You should still have the correct result in `sm`. I do not see any warnings is what I mean by I can't reproduce this. (Actually, I do get a warning from `readLines()` about a missing newline, but that doesn't affect anything negatively.)
