### ISSUE TITLE
exclude part_of

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#11]
Add ability to exclude part_of from entity in OntoTrace query

**Comment by wdahdul** [comment]
More details about this issue: the motivation is from User story 4 (query ontotrace for list of teleost-specific terms; also applies to the miniatures use case). In the KB UI, this query can be done using OntoTrace for OWL expression: hypomaxilla or 'lateral extrascapular' or 'pelvic splint' :

Generated from the Phenoscape Knowledgebase on 2018-11-30 by Ontotrace query:
* taxa: &lt;http://purl.obolibrary.org/obo/VTO_0033666&gt;
* entities: &lt;http://purl.obolibrary.org/obo/UBERON_2001788&gt; or &lt;http://purl.obolibrary.org/obo/UBERON_2002020&gt; or &lt;http://purl.obolibrary.org/obo/UBERON_4200099&gt;</meta>

In RPhenoscape, the query currently can only be done for parts of the search terms only (because part_of is the default): 
pk_get_ontotrace_xml(taxon = "Teleostei", entity = c("hypomaxilla", "lateral extrascapular", "pelvic splint") 

"Generated from the Phenoscape Knowledgebase on 2018-11-30 by Ontotrace query:&#10;
* taxa: &lt;http://purl.obolibrary.org/obo/VTO_0033666&gt;&#10;
* entities: (&lt;http://purl.obolibrary.org/obo/BFO_0000050&gt; some &lt;http://purl.obolibrary.org/obo/UBERON_2001788&gt;) or (&lt;http://purl.obolibrary.org/obo/BFO_0000050&gt; some &lt;http://purl.obolibrary.org/obo/UBERON_2002020&gt;) or (&lt;http://purl.obolibrary.org/obo/BFO_0000050&gt; some &lt;http://purl.obolibrary.org/obo/UBERON_4200099&gt;)"/>

**Comment by hlapp** [comment]
This now possible with the changes in #66, and documented. Simply pass `relation = NA`.
