### ISSUE TITLE
empty ontotrace matrix returned when some terms not found 

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#118]
In the query below, some of the entities weren't found, and an empty matrix was returned. It would be preferable to me to still get the matrix even without the terms that weren't found.

However, if it isn't possible to get the matrix under these conditions, then the summary message should be modified to say "query aborted" or something similar.

[entities-20191028.txt](https://github.com/phenoscape/rphenoscape/files/3852831/entities-20191028.txt)
[taxa_mini_ostariophysi_vto.txt](https://github.com/phenoscape/rphenoscape/files/3852832/taxa_mini_ostariophysi_vto.txt)

```R
nex <- pk_get_ontotrace_xml(taxon = taxa, entity = entities, variable_only = FALSE)

No exact match for ceratobranchial 5 tooth  can be found in database.
Returning the only partial match ceratobranchial 5 tooth (zebrafish)
Could not find "interarcual bone" in the database. Please check your input.
Could not find "suborbital stay" in the database. Please check your input.
```

**Comment by hlapp** [comment]
I agree the current behavior is neither here nor there. One question for designing the right behavior is how lenient the function should be in light of input for which the result will in all likelihood differ from what the user expected.

One option is to be strict. This means if the user asks for something that fails (such as resolving a term label to an IRI) the function stops with an error. The question is what to do in cases of soft failure (failing to find an exact match for label, but a different type of match is found) versus hard failure (label cannot be resolved to IRI). Should these both be treated as failure, or only the latter (with the former resulting in a warning). 

The alternative is to be lenient. That is, warn about all failures, soft or hard, but continue with what's left. The risk in this is that a user puts the function call into a script, which at best will result in the warning to appear at the very end (at which point it may not be straightforward for the user to identify exactly where they were triggered), but can easily result in the user missing the warning altogether, thus assuming erroneously that all is good.

I thought the current behavior is lenient, but that does not seem to be the case given the result you got. My leaning is to change this to the behavior mentioned under strict. For strict behavior, another question is whether failure to find presence-absence character data for the given taxa for one or more of the input terms should be a hard failure, and if so, how to detect it.
