### ISSUE TITLE
Using labels for OWL expressions

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#12]
Allow users to pass OWL expressions by label (currently RPhenoscape requires IDs in the expression). Have RPhenoscape look up the label and replace with IDs for query to Ontotrace using http://kb.phenoscape.org/apidocs/#/Terms/get_term_resolve_label_expression

**Comment by wdahdul** [comment]
Adding an example from Laura's work:
('fin skeleton' or 'adipose fin' or fin or rib or ('skeletal element' and ('part of' some ('axial skeletal system' or splanchnocranium or 'fin skeleton' or 'girdle skeleton' or 'integumental system')))) or ('part of' some ('fin skeleton' or rib or ('skeletal element' and ('part of' some ('axial skeletal system' or splanchnocranium or 'fin skeleton' or 'girdle skeleton' or 'integumental system')))))

and as a reminder (mostly to myself) of why this is needed: the query returns skeletal element parts only, and excludes non-skeletal parts like muscles and other soft tissue structures.

**Comment by wdahdul** [comment]
@hlapp how does this work with IDs? I tried variations of an expression for entity (copied from the dataset tab in Phenex) but they couldn't get them to work:

entities <- c('<http://purl.obolibrary.org/obo/UBERON_0002228>', '(<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0002228>))')

entities <- c('http://purl.obolibrary.org/obo/UBERON_0002228', '(http://purl.obolibrary.org/obo/BFO_0000050 some http://purl.obolibrary.org/obo/UBERON_0002228)')

**Comment by hlapp** [comment]
@wdahdul For OWL expressions you must put angle brackets around every IRI. Otherwise it is not an IRI in the Manchester format.

**Comment by wdahdul** [comment]
I still get an error: 
```
Error: One or more entity names failed to resolve to IRI, unable to continue
In addition: Warning message:
Could not find "<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0000033>" in the database. Please check your input. 
> 
```

**Comment by wdahdul** [comment]
I played around with this a bit, and it appears that brackets aren't needed when querying with single terms, and using brackets returns an error. However, queries with an OWL expression for entity don't work with or without brackets

Using brackets returns an error:
```
taxa <- '<http://purl.obolibrary.org/obo/VTO_0037868>'
entities <- '<http://purl.obolibrary.org/obo/UBERON_0008897>'
nex2 <- pk_get_ontotrace_xml(taxon = taxa, entity = entities, variable_only = FALSE)

Error: One or more taxon and entity names failed to resolve to IRI, unable to continue
In addition: Warning messages:
1: Could not find "<http://purl.obolibrary.org/obo/VTO_0037868>" in the database. Please check your input. 
2: Could not find "<http://purl.obolibrary.org/obo/UBERON_0008897>" in the database. Please check your input. 
```

Same query without brackets works:
```
taxa <- 'http://purl.obolibrary.org/obo/VTO_0037868'
entities <- 'http://purl.obolibrary.org/obo/UBERON_0008897'
nex3 <- pk_get_ontotrace_xml(taxon = taxa, entity = entities, variable_only = FALSE)
```

Query with OWL expression, without brackets, doesn't work:
```
taxa <- 'http://purl.obolibrary.org/obo/VTO_0037868'
entities <- c('http://purl.obolibrary.org/obo/UBERON_0002228', 'http://purl.obolibrary.org/obo/BFO_0000050 some http://purl.obolibrary.org/obo/UBERON_0002228')
nex4 <- pk_get_ontotrace_xml(taxon = taxa, entity = entities, variable_only = FALSE)

Error in get_nexml_data(ontotrace_url, queryseq) : 
  (400) Bad Request: Malformed parameters.

```

**Comment by hlapp** [comment]
This is fixed by the introduction of the `owl` class, and capability of `as.owl()` method to convert from labels, in the v0.3.x releases:
```R
as.owl("'fin spine' and ('part of' some 'pectoral fin')", usesLabels = TRUE)
[1] "<http://purl.obolibrary.org/obo/UBERON_4200075> and (<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0000151>)
```
