### ISSUE TITLE
Add example of OWL expression 

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#13]
In the documentation, please add an example of an OWL expression used to query entities

**Comment by hlapp** [comment]
@wdahdul can you remind me which query this is for.

**Comment by wdahdul** [comment]
Yes, for OntoTrace queries using owl expressions (which currently doesn't work, see #14)

**Comment by hlapp** [comment]
This is now added to the documentation in the upcoming v0.3.0 release:
```r
# query using taxon and/or entity owl expressions resolved from label expressions
taxon_owl <- as.owl("Ictalurus", usesLabels = TRUE)
entity_owl <- as.owl("'fin' or ('part of' some 'fin')", usesLabels = TRUE)
nex <- get_ontotrace_data(taxon = taxon_owl, entity = entity_owl)
```
