### ISSUE TITLE
pk_get_ontotrace warning message

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#148]
```
> absence_mat_median_fins <- pk_get_ontotrace(nexml)
Warning message:
`select_()` is deprecated as of dplyr 0.7.0.
Please use `select()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```

```
backtrace:
  1. rphenoscape::pk_get_ontotrace(nexml)
  2. RNeXML::get_characters(...)
  6. RNeXML::get_level(nex, "otus/otu")
  4. recursion(1, lvl)(nex)
 12. dplyr::select_(., quote(-nexml))
 16. dplyr:::lazy_deprec("select", hint = FALSE)
```

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7
```

**Comment by hlapp** [comment]
@wdahdul let me note as a caveat that Rphenoscape is not approved (or tested) for R 4.x. Also, your output from `sessionInfo()` is missing the most important part, namely the names and versions of loaded packages.

The problem, however, is in RNeXML, not Rphenoscape. Would you mind [posting the issue there](https://github.com/ropensci/RNeXML/issues), with complete output from `sessionInfo()`?

**Comment by wdahdul** [comment]
Thanks Hilmar, I posted the issue: https://github.com/ropensci/RNeXML/issues/250
