### ISSUE TITLE
Save query expression with ontotrace file

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#15]
OntoTrace files obtained from the web UI include the query expression in the "publication notes" field in the nexml file (see attached). 
<img width="1083" alt="screen shot 2018-09-18 at 2 31 24 pm" src="https://user-images.githubusercontent.com/957012/45718226-2b6b5680-bb51-11e8-9fc1-a262d3d33ee1.png">

**Comment by hlapp** [comment]
@balhoff I assume the API returns this as well in the NeXML document? If so this should be available from the NeXML object in R as well. Though I suppose it should be documented how.

**Comment by hlapp** [comment]
This was due to a bug in RNeXML. I reported the issue in ropensci/RNeXML#190, and it was fixed by @cboettig in ropensci/RNeXML#193.

**Comment by hlapp** [comment]
New version of RNeXML is on CRAN now. Upgrading rphenoscape should result in RNeXML being upgraded. See README.
