### ISSUE TITLE
Semantic similarity tests fail

### ISSUE THREAD

**Issue by hlapp** [phenoscape/rphenoscape#153]
This fails on both R 3.6.x and R 4.x.

```
── Failure (test-semsim.R:90:3): Resnik similarity ─────────────────────────────
214 `sm.ic` not equal to `sm.ic2`.
215 81/81 mismatches (average diff: Inf)
216 [1] 2.89 - Inf == -Inf
217 [2] 2.59 - Inf == -Inf
218 [3] 2.59 - Inf == -Inf
219 [4] 1.85 - Inf == -Inf
220 [5] 1.85 - Inf == -Inf
221 [6] 1.85 - Inf == -Inf
222 [7] 2.59 - Inf == -Inf
223 [8] 1.85 - Inf == -Inf
224 [9] 1.75 - Inf == -Inf
225 ...
226
── Failure (test-semsim.R:159:3): profile similarity with Resnik ───────────────
227 max(sm) is not less than -log10(1/corpus_size("taxa")). Difference: Inf
228
```

**Comment by hlapp** [comment]
@balhoff have you changed the API?

**Comment by balhoff** [comment]
@hlapp it was not meant to change, if it did. Can you tell me which services this is using? There is a problem with the ontology hierarchy causing weird similarity results that I mentioned on the Phenoscape call on Friday, which I'm trying to look into (hopefully tomorrow).

**Comment by hlapp** [comment]
The problem is occurrence count zero being returned by the API for owl:Thing, see phenoscape/phenoscape-kb-services#380.

The reason this fails in the tests where it does (trying to compare "hand-computed" IC scores with the function-computed ones) is that the Rphenoscape function defensively converts 0 counts into 1s. That prevents it from returning Infinity (which would result from taking `log(0)`), but in this case it also gives an outsized IC score to a term that is as uninformative as it gets.
