### ISSUE TITLE
Replace for loops with apply

### ISSUE THREAD

**Issue by johnbradley** [phenoscape/rphenoscape#179]
Replace for loops with an appropriate apply function that is more expressive.

**Comment by johnbradley** [comment]
Places current using for loops to review:
https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/KBinfo.R#L15-L17

https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/nexml.R#L96-L103

https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/nexml.R#L114-L119

https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/pk_get_xml.R#L129-L134

https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/pk_study.R#L138-L142

https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/pk_study.R#L163-L167

**Comment by hlapp** [comment]
Interesting. I don't think any one of them presents a good candidate for reaping some performance benefit. Maybe we should just drop this?

**Comment by johnbradley** [comment]
> Interesting. I don't think any one of them presents a good candidate for reaping some performance benefit. Maybe we should just drop this?

Sounds good. Closing this issue.
