### ISSUE TITLE
Automate testing kb.phenoscape API dev endpoint

### ISSUE THREAD

**Issue by johnbradley** [phenoscape/rphenoscape#181]
Github actions run tests [weekly against the production kb.phenoscape API](https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/.github/workflows/check-standard.yaml#L10). 
The production kb.phenoscape API is at https://kb.phenoscape.org/api.
There is also a development kb.phenoscape API: https://stars-app.renci.org/phenoscape-dev-api.
If we included the dev API in our weekly tests we could detect incompatibility issues before they make it to production.

NOTE: Currently we hard code the kb.phenoscape API URL:
https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/pkb_get.R#L123

**Comment by hlapp** [comment]
Perhaps we should make that overridable by an environment variable, e.g., `PHENOSCAPE_API`?
