### ISSUE TITLE
Remove limit work around

### ISSUE THREAD

**Issue by johnbradley** [phenoscape/rphenoscape#183]
Previously the [kb.phenoscape API](https://kb.phenoscape.org/apidocs/#/) did not allow fetching all the rows for a request. To work around this the rphenoscape code set limit to high integer values. The kb.phenoscape API now allows passing limit=0 to fetch all rows: https://github.com/phenoscape/phenoscape-kb-services/issues/64. Update the code to use the limit=0 to request all rows.

**Comment by balhoff** [comment]
I just wanted to note that the fix hasn't been deployed yet—it will be on the dev server first and will probably be part of getting the latest `master` commits and new database happy with rphenoscape. But if we need to patch it into the version running on production sooner, we can do that.

**Comment by johnbradley** [comment]
@balhoff No need to push the fix to production sooner. This issue can wait for your normal release cycle.

**Comment by johnbradley** [comment]
@balhoff Is the fix for limit deployed in the v2-beta KB API (https://dev.phenoscape.org/api/v2-beta) ?

**Comment by balhoff** [comment]
Yes, it should be there now.

**Comment by johnbradley** [comment]
Fixed by #227
