### ISSUE TITLE
Print function for phenotype objects fails if there are no states

### ISSUE THREAD

**Issue by johnbradley** [phenoscape/rphenoscape#190]
Printing some Phenotype objects fail with an error.
Example from an R session:
```
> as.phenotype("http://purl.obolibrary.org/obo/MP_0030825")
Phenotype 'decreased femur size'
Linked to states:
Error in x$states[, c("label", "character.label", "study.label")] : 
  incorrect number of dimensions
```
The error is coming from the `print.phenotype` function:
https://github.com/phenoscape/rphenoscape/blob/c1376ddef0c2577cee05fc535487fee6b35ff9c2/R/phen_obj.R#L224-L229

The data is coming from the `/phenotype/info` kb.phenoscape.org API endpoint.

The response I get from [get_phenotype_info](https://kb.phenoscape.org/apidocs/#/Phenotypes/get_phenotype_info) returns an empty array for states. `{..."states": [],...}`.

I have yet to find a phenotype IRI that doesn't have this error when printing.

**Comment by balhoff** [comment]
Not all phenotypes are linked to states (which are for evolutionary data). This is a model organism phenotype. However looking at the phenotype label I have a guess that this one could be inferred as equivalent to an evolutionary phenotype annotation, which might result in its getting returned unexpectedly in an evolutionary data query. Are you encountering this IRI in a context where it would be expected to be connected to a state (from an evolutionary query)? If so there may be something to fix in the server query.

**Comment by hlapp** [comment]
Yeah the problem is no states, and I've encountered this before.

I agree though in principle the print function shouldn't fall over if there are no states, even if expecting the presence of states should be justified for evolutionary phenotypes (which all of the phenotypes are, or at least should be, that are returned by `get_phenotypes()`). I've changed the title to more accurately reflect the issue. It's not necessarily high priority, but I agree good to have a record of it so we can fix it.

**Comment by hlapp** [comment]
Actually let me correct myself. There _was_ a fix to this problem:
https://github.com/phenoscape/rphenoscape/blob/c1376ddef0c2577cee05fc535487fee6b35ff9c2/R/phen_obj.R#L145
which is in the `is_valid_phenotype()` test.

So apparently the API endpoint used to not include the key `states` at all if there weren't any states, but now it does, with an empty array as value. This should be easy to fix, just change the test to `! (is.null(nrow(p$states)) || nrow(p$states) == 0)`.

**Comment by johnbradley** [comment]
I think the `res <- ! is.null(nrow(p$states))` line would catch the problem, but before that there is a check to see if a label has a value:

https://github.com/phenoscape/rphenoscape/blob/c1376ddef0c2577cee05fc535487fee6b35ff9c2/R/phen_obj.R#L142-L145

Since this item has a `label` ("decreased femur size") the `states` are not checked and `is_valid_phenotype` returns TRUE.
Perhaps the fix is to only check for valid states?

**Comment by hlapp** [comment]
Well, the documentation currently says the following: _An object is a valid phenotype object if it is of type "phenotype" and its ID has been found in the database_.

The definition still sounds right to me. So how do we determine whether an object's phenotype ID has been found in the database? Right now, the answer according to the code is, the ID has been found in the database if we were able to retrieve a label, or if there's no label, if we there are at least states.

I'm not sure why that's not the correct answer. Gene phenotypes don't have states (but at least currently have labels, given that they come from pre-composed phenotype ontologies), and they are valid phenotypes. I guess the question is, if a phenotype has neither a label nor states, could it still be a valid phenotype by the above definition. Possibly, if there's at least a single piece of information other than the identifier as evidence that the ID is indeed in the database. As for whether a phenotype ID that is in the database but for which no other phenotype object-pertinent information can be surfaced other than the ID, returning FALSE for these is I think at the very least an acceptable error, and possibly even defensible as the right choice.

So I think the real mistake of the code is to assume that a phenotype object found to be valid by `is_valid_phenotype()` is expected to have states. That need not be true.
