### ISSUE TITLE
as.phenotype print display

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#198]
In the as.phenotype print display (below), shouldn’t “Entities” and “Qualities” be singular because it’s only possible to display one entity and one quality (and one related entity if applicable) for a phenotype? 

Also, I think replacing “Towards” with “Related entity” will help with understanding the output. 

```
> obj
Phenotype 'basihyal bone absent'
Linked to states:
               label character.label           study.label
1  states 0, 1 and 2        Basihyal Imamura et al. (2005)
2 absent (unordered)        Basihyal Imamura et al. (2005)
3             Absent   Basihyal bone  Mabee et al.  (2011)
4    basihyal absent        Basihyal       De Pinna (1993)

Entities:
    multicellular organism <http://purl.obolibrary.org/obo/UBERON_0000468>
Qualities:
    lacks all parts of type <http://purl.obolibrary.org/obo/PATO_0002000>
Towards:
    basihyal bone <http://purl.obolibrary.org/obo/UBERON_0011618>

No information about taxa exhibiting this phenotype.
```

**Comment by hlapp** [comment]
I think there could be multiple in case of nested expressions. The [API endpoint](https://kb.phenoscape.org/apidocs/#/Phenotypes/get_phenotype_info) does use plural in its JSON response format.

@balhoff mind to weigh in here?

**Comment by balhoff** [comment]
Yes, there can be more than one non-redundant Entity or Quality after inference.

**Comment by hlapp** [comment]
> Also, I think replacing “Towards” with “Related entity” will help with understanding the output.

Possibly. It'd be nice to have some others who are part of the target audience weigh in, for example @uyedaj or @diegosasso.

**Comment by hlapp** [comment]
Moved outstanding question to #250 and closing this one.
