### ISSUE TITLE
Some tests on Release are failing due to timeouts fetching data from API

### ISSUE THREAD

**Issue by hlapp** [phenoscape/rphenoscape#208]
> The github action tests are failing due to timeouts fetching data from kb.phenoscape.org/api.
> I don't think these problems are related to changes here.

I agree they don't seem related to changes here. But the failures also appear reproducible, and only so for the release version. This suggests that a more current release of the cURL library or rCurl introduce this 10s timeout (or do not automatically extend it anymore?), and that we may need to explicitly request a longer timeout.

_Originally posted by @hlapp in https://github.com/phenoscape/rphenoscape/issues/197#issuecomment-856220061_

**Comment by johnbradley** [comment]
The errors in question have occurred on both the 3.6 and release version of R tested via github actions.
Example failure with R 3.6: https://github.com/phenoscape/rphenoscape/actions/runs/916125533
Example failure with R 4.1.0(release): https://github.com/phenoscape/rphenoscape/actions/runs/916134218
An example of the error looks like this:
```
> corpus_size("taxa")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [kb.phenoscape.org] Connection timed out after 10001 milliseconds
```
When run from the R interpreter on my Mac the `corpus_size("taxa")` function finishes in less than a second.

**Comment by johnbradley** [comment]
The errors have stopped occurring. I re-ran the tests via github actions on multiple branches and they all work now.
There have been no changes to fix this problem on the kb.phenoscape.org/api.

**Comment by hlapp** [comment]
Great! My understanding (from researching the error on the internet) is that the timeout reached wasn't for data being returned, but for the connection to be established. Indeed establishing the connection shouldn't take >10s, and if it does it suggests a problem with one's DNS and/or internet proxy. It could, I think, also indicate a problem with a DDoS defense configuration of the destination server (or the infrastructure hosting it).

I guess we don't know whether something changed on GitHub's infrastructure, or for the RENCI servers. Let's see whether this issue returns at a frequency or duration sufficiently annoying to warrant some action about protecting from it, but for now it seems we can close this?

@balhoff any thoughts or comments?

**Comment by balhoff** [comment]
I don't know what could have been the cause. If this starts to happen again, let me know and we can bring in the RENCI sys admin team.

**Comment by johnbradley** [comment]
I had this timeout error happen again when running tests in github actions. I re-ran the tests in github actions and they worked fine.

**Comment by hlapp** [comment]
@johnbradley I think this can be closed?

**Comment by johnbradley** [comment]
@hlapp I still see these errors occasionally on github. Re-running the test fixes it.

**Comment by hlapp** [comment]
So leave it open for now until they have disappeared for some time, or did you mean to say yes, we can close this?

**Comment by johnbradley** [comment]
I would like to leave this open for now. Even if it's just to add some kind of timeout/retry retry running the tests.

**Comment by hlapp** [comment]
This is essentially a more narrow form of #252, so I'm closing this one here.
