### ISSUE TITLE
Update API link in documentation

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#224]
The first link on this page: https://rphenoscape.phenoscape.org/articles/rphenoscape.html 
to the  [Phenoscape Knowledgebase web API](https://stars-app.renci.org/apidocs/) leads to a 404 error

**Comment by balhoff** [comment]
It needs to be changed to https.

**Comment by wdahdul** [comment]
Also the same link at the bottom of this page under "Package Usage Information:: https://rphenoscape.phenoscape.org/index.html

**Comment by hlapp** [comment]
@balhoff can't you just redirect from http to https? That would be good practice anyway as the URL may well be out in the wild too. Any reason that can't be done?

**Comment by balhoff** [comment]
No reason not to - I need to fix this.

**Comment by johnbradley** [comment]
The redirect has been implemented. The link in the documentation now works for me.

**Comment by hlapp** [comment]
Fixed server-side.
