### ISSUE TITLE
Add support for new dev v2-beta KB API

### ISSUE THREAD

**Issue by johnbradley** [phenoscape/rphenoscape#243]
There is a new API endpoint with some changes to the phenoscape KB API.
This API replaces the `corpus_graph=<IRI>` parameter with `corpus=taxa|states`.
The current URL for this API is: https://dev.phenoscape.org/api/v2-beta/

**Comment by johnbradley** [comment]
# API changes to endpoints used in rphenoscape

[New v2-beta Swagger Docs](https://dev.phenoscape.org/api/v2-beta/docs/)
[Old v2-beta Swagger Docs](https://kb.phenoscape.org/api/v2-beta/docs/)

## /similarity/corpus_size
**Change**
Required `corpus_graph` parameter was replaced by required `corpus` parameter.
Values for `corpus_graph` were http://kb.phenoscape.org/sim/taxa and http://kb.phenoscape.org/sim/genes.
Values for `corpus` are `taxa` and `states`.

**rphenoscape usage**
https://github.com/phenoscape/rphenoscape/blob/6b59eda736431a8f25e08969eebe2dcbbf3c3150/R/term-weights.R#L166-L174

## /similarity/matrix
**Change**
Added optional `corpus` argument. Allowed values are `taxa` and `states`.

**rphenoscape usage**
https://github.com/phenoscape/rphenoscape/blob/3ea9a2069f98bc29060a013a2191653d3c293b4c/R/semsim.R#L78-L81

## /similarity/frequency
**Change**
Required `corpus_graph` parameter was replaced by required `corpus` and `type` parameters.
I think values for corpus_graph were http://kb.phenoscape.org/sim/taxa and http://kb.phenoscape.org/sim/genes.
Values for `corpus` are `taxa` and `states`.
Values for `type` are `phenotype` and `anatomical_entity`.

**rphenoscape usage**
https://github.com/phenoscape/rphenoscape/blob/3ea9a2069f98bc29060a013a2191653d3c293b4c/R/term-weights.R#L66-L73

**Comment by hlapp** [comment]
@johnbradley I think this is complete now and can be closed, right?
