### ISSUE TITLE
error accessing KB API through rphenoscape

### ISSUE THREAD

**Issue by megbalk** [phenoscape/rphenoscape#275]
I am working through the [paramo tutorial](https://phenoscape.org/scate-shortcourse/articles/PARAMO.html) in preparation for the SCATE TraitFest, and am running into the following error:

```
nex <- lapply(terms, get_ontotrace_data, taxon=taxon, variable_only=TRUE)
Error in get_nexml_data(pkb_api("/ontotrace"), queryseq) : 
  (500) Internal Server Error: There was an internal server error.
```

May I get help with this?

Note: in the tutorial the argument originally was `nex <- lapply(terms, pk_get_ontotrace_xml, taxon=taxon, variable_only=TRUE)`, but I got this error and changed the argument:

```
Error in get_nexml_data(pkb_api("/ontotrace"), queryseq) : 
  (500) Internal Server Error: There was an internal server error.
In addition: Warning message:
'FUN' is deprecated.
Use 'get_ontotrace_data' instead.
See help("Deprecated") 
```

**Comment by johnbradley** [comment]
@megbalk Are you using the values for "terms" and "taxon" from the PARAMO tutorial?
I ran the following without getting the error:
```
> terms <- c("dermatocranium", "paired fin", "barbel") 
> taxon <- "Siluriformes"  
> nex <- lapply(terms, get_ontotrace_data, taxon=taxon, variable_only=TRUE)
> 
```
You are correct to replace `pk_get_ontotrace_xml` with `get_ontotrace_data`, but that shouldn't be related to your error here. What version of rphenoscape are you using?

**Comment by johnbradley** [comment]
I believe the error is from the `/ontotrace` endpoint of the kb phenoscape API server (https://kb.phenoscape.org/api/v2 by default). @balhoff Can you see anything in the logs for that server?

**Comment by megbalk** [comment]
I should be using the latest version (I recently installed it, so I assume it pulled the latest)

**Comment by balhoff** [comment]
@megbalk @johnbradley could you retry now? We had some service restarts here, and the owlery service, which is used by ontotrace, takes a while to start.

**Comment by megbalk** [comment]
@balhoff it works! thanks!
