### ISSUE TITLE
Fix automated tests

### ISSUE THREAD

**Issue by johnbradley** [phenoscape/rphenoscape#276]
The scheduled automated tests failed today in one test:
```
Error: custom user agent is set (@test-kb.R#5)
```
Initially this test [failed in r3](https://app.circleci.com/pipelines/github/phenoscape/rphenoscape/140/workflows/235f8621-8f94-4096-a488-2b7ebb1e163b/jobs/307).
Rerunning this test [failed in r4](https://app.circleci.com/pipelines/github/phenoscape/rphenoscape/140/workflows/fc137a6b-fccd-4cfe-b54c-fa834b34493e/jobs/309)

**Comment by johnbradley** [comment]
Here is the code that failed:
https://github.com/phenoscape/rphenoscape/blob/de2736b497b45dae8c365add8bd08a520b45c7c2/tests/testthat/test-kb.R#L3-L5
Rerunning a third time both tests passed.
Since this uses an external server perhaps that server was just temporary overloaded.

**Comment by hlapp** [comment]
I agree, it's one of those free services that probably just gets overloaded at difficult to predict times. Ideally we could move this to a local test, using some kind of mock http service if one exists.

We certainly can't have a test like this run at CRAN anyway without protecting from failure. (_Packages which use Internet resources should fail gracefully with an informative message if the resource is not available or has changed (and not give a check warning nor error)._ from the [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html#Source-packages))
