### ISSUE TITLE
Change prefix for exported package API functions

### ISSUE THREAD

**Issue by hlapp** [phenoscape/rphenoscape#38]
Presently, exported functions of the package API use `pk_` as the prefix, which is short but has several shortcomings. For example, it is not a prefix we use anywhere else in Phenoscape, yet it is frequently used as an abbreviation for the entirely unrelated concept of _primary key_.

We should change this either to one that's consistent with usage elsewhere in Phenoscape (for example, `pkb_` for _Phenoscape Knowledgebase_), or to no prefix at all. The latter would require clients to use the package as prefix (e.g., `rphenoscape::anatomical_detail()`) to avoid ambiguity.

Using the package as prefix is generally considered good programming practice in R, because it makes it clear in code where (which package) a function is coming from that's being invoked.

Finally, this change should arguably be made sooner than later, i.e., while there are few users potentially impacted by it (and few functions for which mapping the old name to the new one would need to be considered to maintain backwards compatibility).

**Comment by hlapp** [comment]
@wdahdul @uyedaj @sergeitarasov if you have any opinions on this, certainly feel free to share. My leaning would be no prefix in exported function names, but I can well be convinced otherwise.

**Comment by wdahdul** [comment]
Yes, following up after our project call today, I also would prefer no prefix be used.

**Comment by johnbradley** [comment]
Here are the remaining exported functions starting with "pk_" from `baseline-v0.3.0`.

Functions from [pk_terms.R](https://github.com/phenoscape/rphenoscape/blob/baseline-v0.3.0/R/pk_terms.R):
- [pk_taxon_detail](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_terms.R#L34)
- [pk_anatomical_detail](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_terms.R#L68)
- [pk_phenotype_detail](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_terms.R#L73)
- [pk_gene_detail](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_terms.R#L79)
- [pk_is_extinct](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_terms.R#L105)

Functions from [pk_is_descendant.R](https://github.com/phenoscape/rphenoscape/blob/baseline-v0.3.0/R/pk_is_descendant.R):
- [pk_is_descendant](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_is_descendant.R#L42)
- [pk_is_ancestor](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_is_descendant.R#L49)

### Create NeXML
Functions from [pk_get_xml.R](https://github.com/phenoscape/rphenoscape/blob/baseline-v0.3.0/R/pk_get_xml.R):
- [pk_get_ontotrace_xml](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_get_xml.R#L59)
- [pk_get_study_xml](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_get_xml.R#L124)

### Extract data from NeXML
NOTE: There is a separate issue to evaluate keeping/reworking these NeXML extracting functions: #172.

Functions from [pk_ontotrace.R](https://github.com/phenoscape/rphenoscape/blob/baseline-v0.3.0/R/pk_ontotrace.R):
- [pk_get_ontotrace](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_ontotrace.R#L23)
- [pk_get_ontotrace_meta](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_ontotrace.R#L34)

Functions from [pk_study.R](https://github.com/phenoscape/rphenoscape/blob/baseline-v0.3.0/R/pk_study.R)
- [pk_get_study](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_study.R#L99)
- [pk_get_study_meta](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_study.R#L124)

**Comment by johnbradley** [comment]
@hlapp For the next part of this I was planning to rename [pk_get_ontotrace_xml](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_get_xml.R#L59) to `get_ontotrace_xml` and [pk_get_study_xml](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_get_xml.R#L124) to `get_study_xml` unless you have other suggestions. `pk_get_study_xml` looks like it [should have a verbose flag](https://github.com/phenoscape/rphenoscape/blob/e9aed6e58af7bce3b5034dfbe0618c8994c1456c/R/pk_get_xml.R#L124-L126). Do you have any other feedback on these two functions before I begin?

**Comment by hlapp** [comment]
I'm inclined to simply rename to `get_ontotrace()` and `get_study()`. The `_xml` suffix is solely there to indicate the return type, but the return type isn't actually XML (it is a `nexml` R object, which can be converted to XML), and we don't do this (using suffix to hint at return type) for any other return type.

Perhaps worth considering is to use a suffix indicating that this is retrieving a data object, not an "ontotrace" (which if anything, is the name of the algorithm) or a "study" (though colloquially we often do use "study" synonymous with "data of the study". So that would yield `get_ontotrace_data()` and `get_study_data()`.

Thoughts?

**Comment by wdahdul** [comment]
I agree about dropping the `_xml` suffix, and I like `get_ontotrace_data` and `get_study_data`, which seem clearer in meaning to me than the shorter names `get_ontotrace` or `get_study`.

**Comment by wdahdul** [comment]
also, I don't think the renaming of `pk_get_ontotrace` and `pk_get_study` has been discussed yet, so adding a comment about that. I get confused distinguishing these from the functions that retrieve nexml objects. Consider renaming to something like `get_ontotrace_dataframe` and `get_study_dataframe`?

**Comment by johnbradley** [comment]
The `get_ontotrace_data()` and `get_study_data()` function names sound good to me.

**Comment by hlapp** [comment]
> I don't think the renaming of `pk_get_ontotrace` and `pk_get_study` has been discussed yet

We've started discussing those, but it's a different issue. The first question for these is to clarify why they are needed at all (the functionality at least in theory should meanwhile be available directly from the RNeXML package), and if there's something that's needed, what their most suitable place would be (i.e., in Rphenoscape or RNeXML).

**Comment by hlapp** [comment]
🎉🎉🎉
