### ISSUE TITLE
Use POST instead of GET for large request data

### ISSUE THREAD

**Issue by hlapp** [phenoscape/rphenoscape#43]
For some Phenoscape API methods, such as the Ontotrace endpoint and others that allow supplying possibly long lists, the request parameters can get too large for the server to accept them, resulting in a 414 error. These endpoints will also accept POST requests, for which the parameters are put into the request body rather than URL. The respective Rphenoscape functions need to be changed to either use POST if the request parameters length exceeds a certain size, or to always use POST. (There shouldn't really be a reason not to always use POST; if there's any protocol overhead penalty for POST versus GET, it should be negligible compared to the time it takes to compose the response.)

Candidates include the following:
* [x] `pk_get_ontotrace_xml()`

**Comment by hlapp** [comment]
@balhoff I notice that the KB API documentation doesn't state that POST is supported as well. If POST is indeed supported, could this please be fixed?

**Comment by balhoff** [comment]
I don't think POST is supported yet for this one, but it can be added.

**Comment by balhoff** [comment]
POST should be working now, and it is in the Swagger docs.
