### ISSUE TITLE
Add examples for phenotype detail and classification

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#52]
Need examples added to the documentation for how to specify a phenotype when using pk_phenotype_detail and pk_phenotype_class.

**Comment by wdahdul** [comment]
I looked at how these are defined in pk_classification.R and pk_terms.R, and actually they take PATO terms as arguments (see below).  How about renaming the functions as pk_quality_class and pk_quality_detail to clear up their meaning?


```
pk_phenotype_class <- function(x, verbose=TRUE) {
  pk_class(x, as = "pato", verbose)
```

```
pk_phenotype_detail <- function(term, verbose=FALSE) {
  pk_details(term, as = "pato", verbose)
```

> pk_phenotype_class('rhomboid')

$label
[1] "rhomboid"

$subClassOf
                                          @id         label
1 http://purl.obolibrary.org/obo/PATO_0002317 parallelogram

$equivalentTo
list()

$superClassOf
list()

$`@id`
[1] "http://purl.obolibrary.org/obo/PATO_0001938"

**Comment by hlapp** [comment]
I think the question needs to be what is best for the targeted user. The main goal of Rphenoscape is not to create a perfect mirror of the KB API, but to make use cases easy that matter to our target users.

I suspect our target users will think more about "phenotype" (or "trait") than understand the role of PATO quality terms. Though perhaps there _are_ good comparative trait analysis use cases where inspection of PATO quality terms comes into play.

**Comment by pmabee** [comment]
Let's call it pk_phenotypic_quality to match the KB (see: http://beta.phenoscape.org/#/facet )

**Comment by hlapp** [comment]
As per #185,  `pk_phenotype_detail()` will become `phenotypic_quality_term_info()` in the upcoming v0.3.x release series. `pk_phenotype_class()` will then be rolled into `term_classification()`, see #163. Note also that `X_term_info()` functions are being refactored to return a `terminfo` class object, see #192.

Although the changes aren't released quite yet, it's not too far away, and hence I'm inclined to close this now. OK @wdahdul?

**Comment by wdahdul** [comment]
Yes, sounds fine to me. I'll close this ticket.
