### ISSUE TITLE
ontotrace not returning results for specific query

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#54]
pk_get_ontotrace_xml(taxon = "Siluriformes", entity = "bony plate") returns an empty file.  Querying ontotrace in the KB UI returns 1 character and 543 taxa.

**Comment by pmabee** [comment]
Related to #55

**Comment by hlapp** [comment]
I'm going to keep this one open to test that indeed it is the same issue.

**Comment by hlapp** [comment]
With #66 this now does return the same result.
