### ISSUE TITLE
Links in Package Usage Info section of documentation

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#57]
This page: http://rphenoscape.phenoscape.org/ links to itself in the Package Usage Information section. Should it link to a different page, or to the Get Started tab? 

Also, that section mentions the use cases but those are on a different page. I think the link should go to https://github.com/phenoscape/rphenoscape/wiki/User-Stories?

**Comment by hlapp** [comment]
> This page: http://rphenoscape.phenoscape.org/ links to itself in the Package Usage Information section. Should it link to a different page, or to the Get Started tab?

No, it should link here. This is generated from the package README, and in the README this link is _not_ to itself.

> Also, that section mentions the use cases but those are on a different page. I think the link should go to https://github.com/phenoscape/rphenoscape/wiki/User-Stories?

Indeed, I'll fix this.
