### ISSUE TITLE
get character and taxon totals for ontotrace matrix

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#64]
Following up on last week's team call, we discussed needing a function that gives the number of characters and taxa in an ontotrace matrix

**Comment by hlapp** [comment]
This will be fixed in full once RNeXML has its next release to CRAN, which will include ropensci/RNeXML#237.

**Comment by hlapp** [comment]
RNeXML 2.4.0 is now on CRAN, and will be minimally required in the next release of RPhenoscape.
