### ISSUE TITLE
write.nexml error

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#68]
When trying to save an OntoTrace file, get this error: 
Error: could not find function "write.nexml"

**Comment by hlapp** [comment]
@wdahdul can you give the complete sequence of commands to reproduce this error.

**Comment by wdahdul** [comment]
nex <- pk_get_ontotrace_xml(taxon = "Ictalurus", entity = "fin", variable_only = FALSE) 
write.nexml(nex, file="Ictalurus-fin.xml")

Error: could not find function "write.nexml"

**Comment by hlapp** [comment]
`write.nexml()` is from the RNeXML package, so to invoke it you either need to have the RNeXML package attached (`library("RNeXML")`), or you need to prefix the namespace (`RNeXML::write.nexml()`).

Is this documented misleadingly somewhere in RPhenoscape?

**Comment by wdahdul** [comment]
I needed to load the library in this session. It does work for me now.
