### ISSUE TITLE
pk_get_study_xml results

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/rphenoscape#69]
Running this:
Nex <-  pk_get_study_xml('http://dx.doi.org/10.1111/j.1096-3642.2004.00109.x')
study_matrix <- pk_get_study(nex)
study_matrix[[1]][1:5, 1:5]

Doesn't display the same metadata elements as in the example in http://rphenoscape.phenoscape.org/articles/rphenoscape.html

**Comment by hlapp** [comment]
@wdahdul you're not using the same sequence of commands, so I wouldn't expect it to show the same. Or do you have reason to believe that the first element in the `slist$id` array in the vignette is indeed `'http://dx.doi.org/10.1111/j.1096-3642.2004.00109.x'`?

**Comment by wdahdul** [comment]
I couldn't replicate the problem, so closing this item.
