### ISSUE TITLE
pk_anatomical_detail() fails to return multiple exact matches

### ISSUE THREAD

**Issue by uyedaj** [phenoscape/rphenoscape#96]
Update results in a different exact match being returned, which breaks my vignette. I need the UBERON id not the CARO id for "anatomical entity". Should be able to specify which is returned? Reports multiple exact matches but no way to access alternative matches....

```
pk_anatomical_detail("anatomical entity")
```

**Comment by balhoff** [comment]
@uyedaj I think @hlapp was going to expose the `isDefinedBy` property in this. If you see an option like that, try passing `http://purl.obolibrary.org/obo/uberon.owl` or `UBERON`. Unfortunately I'm not too familiar with the R API.

**Comment by hlapp** [comment]
I can expose the ability to narrow the ontology here as well. Right now it will narrow to any anatomy ontology that's in the database (CARO being one of them).

@uyedaj can you point me to where you are using this? If all you need is the id (IRI), then this wouldn't be the best method anyway. Instead, you would use `pk_get_iri()` for that purpose:
```R
pk_get_iri("anatomical entity", as = "uberon")
[1] "http://purl.obolibrary.org/obo/UBERON_0001062"
```
If you do need the output from `pk_anatomical_detail()` then pass the IRI to it:
```R
pk_anatomical_detail(pk_get_iri("anatomical entity", as = "uberon"))
              label
1 anatomical entity
                                                                                                                                                                 definition
1 Biological entity that is either an individual member of a biological species or constitutes the structural organization of an individual member of a biological species.
                                             id
1 http://purl.obolibrary.org/obo/UBERON_0001062
```

**Comment by hlapp** [comment]
And I should add, if in fact you do want all exact matches, then use `find_term()`:
```R
find_term("anatomical entity", matchTypes = c("exact"))
                                             id             label
1   http://purl.obolibrary.org/obo/CARO_0000000 anatomical entity
2 http://purl.obolibrary.org/obo/UBERON_0001062 anatomical entity
                                isDefinedBy matchType
1   http://purl.obolibrary.org/obo/caro.owl     exact
2 http://purl.obolibrary.org/obo/uberon.owl     exact
```

**Comment by uyedaj** [comment]
Great, thank you @hlapp; I'll just use `pk_get_iri()` for this then.
